### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by ng-hai** [rsms/figplug#2]
I got this error when running the plugin initialized with `-react` template
<img width="446" alt="image" src="https://user-images.githubusercontent.com/19520278/62832614-3e9c7e80-bc5b-11e9-9855-1e0fa2479527.png">

**Comment by brianlovin** [comment]
Likewise, can't get a react UI build running

**Comment by rememberlenny** [comment]
I also couldn't get this working. I went with another repo: https://github.com/nirsky/figma-plugin-react-template

@ng-hai @brianlovin

**Comment by HYngHwang** [comment]
https://www.figma.com/plugin-docs/api/api-overview/

figma.createRectangle()
figma.closePlugin()

**Comment by HYngHwang** [comment]
◆☆ Roman Nurik : Stars ☆◆

rsms/figplug
Figma plugin builder
★ 109  ● TypeScript

**Comment by rsms** [comment]
What exact steps can be taken to reproduce this issue?

**Comment by brianlovin** [comment]
@rsms I got this error out of the box when scaffolding a plugin with the React UI. E.g.:
- run the command: `figplug init -react my-plugin`
- build and watch: `figplug build -w my-plugin`
- the above error prevents the plugin from running

Screenshot of what I get when I init, build, and run a -react plugin from scratch:
<img width="1290" alt="Screenshot 2019-10-23 10 43 11" src="https://user-images.githubusercontent.com/1923260/67404864-f5817880-f581-11e9-9def-98af000abfea.png">

**Comment by rsms** [comment]
Aaah! I see. This is an error in the resulting app, not necessarily in figplug (the program.) Thanks @brianlovin — this narrows down the test cases.

**Comment by rsms** [comment]
It seems the culprit is that the latest react library tries to unconditionally access `process.env.NODE_ENV` which is of course not set in a web browser. A fix should land soon.

**Comment by rsms** [comment]
New release has been published to npm with the fixes included.
https://www.npmjs.com/package/figplug

To upgrade:

```sh
npm install -g figplug
```

You may also want to run `init` in your projects to update figma and figplug type definitions:

```sh
cd my-project
figplug -v init  # -v flag enables verbose logging
```

**Comment by maxkrieger** [comment]
@rsms I think this is still an issue. While

> ```shell
> figplug -v init
> ```

works, doing it with the `-react` flag results in the same problem.
